repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
        stages: [pre-commit, manual]
    -   id: end-of-file-fixer
        stages: [pre-commit, manual]
    -   id: check-yaml
        stages: [pre-commit, manual]
    -   id: check-added-large-files
        stages: [pre-commit, manual]

-   repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
    -   id: isort
        name: isort (python)
        args: ["--profile", "black"]
        stages: [pre-commit, manual]

-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
        args: ["--target-version=py310"]
        stages: [pre-commit, manual]

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args:
            - --max-line-length=88
            - --extend-ignore=D100,D101,D102,D103,D104,D105,D106,D107

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
    -   id: mypy
        additional_dependencies:
          - types-requests
          - types-PyYAML
        stages: [pre-commit, manual]
